# Generated by Django 4.2.6 on 2023-10-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
